#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gplayapidev"
primary_region = "sin"

[build]
  image = "ghcr.io/srikanthlogic/google-play-api:dev"

[http_service]
  protocol = "tcp"
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.concurrency]
    type = "requests"
    soft_limit = 400
    hard_limit = 500

[env]
  COUNTRY_OF_QUERY = "IN"
  LOGGING = true